// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "angular",
		Extensions:     nil,
		Language:       AngularLanguage,
		HighlightQuery: angularHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("angular"),
	})
}

const angularHighlightQuery = ""
