// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "apex",
		Extensions:     nil,
		Language:       ApexLanguage,
		HighlightQuery: apexHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("apex"),
	})
}

const apexHighlightQuery = ""
