// Code generated by ts2go batch, then manually extended with TagsQuery.

package grammars

const asmTagsQuery = `
(ident) @name @definition.function
`

func init() {
	Register(LangEntry{
		Name:               "asm",
		Extensions:         []string{".s", ".asm"},
		Language:            AsmLanguage,
		HighlightQuery:     asmHighlightQuery,
		TagsQuery:          asmTagsQuery,
		TokenSourceFactory: defaultTokenSourceFactory("asm"),
	})
}

const asmHighlightQuery = ""
