// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "astro",
		Extensions:     nil,
		Language:       AstroLanguage,
		HighlightQuery: astroHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("astro"),
	})
}

const astroHighlightQuery = "(tag_name) @tag\n(erroneous_end_tag_name) @tag.error\n(doctype) @constant\n(attribute_name) @attribute\n(attribute_value) @string\n(comment) @comment\n\n[\n  \"<\"\n  \">\"\n  \"</\"\n] @punctuation.bracket\n"
