// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "bass",
		Extensions:     nil,
		Language:       BassLanguage,
		HighlightQuery: bassHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("bass"),
	})
}

const bassHighlightQuery = ""
