// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "beancount",
		Extensions:     nil,
		Language:       BeancountLanguage,
		HighlightQuery: beancountHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("beancount"),
	})
}

const beancountHighlightQuery = ""
