// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "blade",
		Extensions:     nil,
		Language:       BladeLanguage,
		HighlightQuery: bladeHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("blade"),
	})
}

const bladeHighlightQuery = "; inherits: html\n\n[\n  (directive)\n  (directive_start)\n  (directive_end)\n] @tag\n\n[\n  (php_tag)\n  (php_end_tag)\n  \"{{\"\n  \"}}\"\n  \"{!!\"\n  \"!!}\"\n  \"(\"\n  \")\"\n] @punctuation.bracket\n"
