// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "chatito",
		Extensions:     nil,
		Language:       ChatitoLanguage,
		HighlightQuery: chatitoHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("chatito"),
	})
}

const chatitoHighlightQuery = "; Punctuation\n[\n  \"%[\"\n  \"@[\"\n  \"~[\"\n  \"*[\"\n  \"]\"\n  \"(\"\n  \")\"\n] @punctuation.bracket\n\n[\n  eq: _\n  \",\"\n] @punctuation.delimiter\n\n[\n  \"%\"\n  \"?\"\n  \"#\"\n] @punctuation.special\n\n; Entities\n(intent) @module\n\n(slot) @type\n\n(variation) @variable.member\n\n(alias) @embedded\n\n(number) @number\n\n(argument\n  key: (string) @attribute\n  value: (string) @string)\n\n(escape) @string.escape\n\n; Import\n\"import\" @keyword\n\n(file) @string.special\n\n; Text\n(word) @markup\n\n; Comment\n(comment) @comment\n"
