// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "clojure",
		Extensions:     []string{".clj", ".cljs", ".cljc", ".edn"},
		Language:       ClojureLanguage,
		HighlightQuery: clojureHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("clojure"),
	})
}

const clojureHighlightQuery = ";; Literals\n\n(num_lit) @number\n\n[\n  (char_lit)\n  (str_lit)\n] @string\n\n[\n (bool_lit)\n (nil_lit)\n] @constant.builtin\n\n(kwd_lit) @constant\n\n;; Comments\n\n(comment) @comment\n\n;; Treat quasiquotation as operators for the purpose of highlighting.\n\n[\n \"'\"\n \"`\"\n \"~\"\n \"@\"\n \"~@\"\n] @operator\n"
