// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "cobol",
		Extensions:     []string{".cob", ".cbl", ".cpy"},
		Language:       CobolLanguage,
		HighlightQuery: cobolHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("cobol"),
	})
}

const cobolHighlightQuery = ""
