// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "comment",
		Extensions:     nil,
		Language:       CommentLanguage,
		HighlightQuery: commentHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("comment"),
	})
}

const commentHighlightQuery = ""
