// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "commonlisp",
		Extensions:     nil,
		Language:       CommonlispLanguage,
		HighlightQuery: commonlispHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("commonlisp"),
	})
}

const commonlispHighlightQuery = ""
