// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "cooklang",
		Extensions:     nil,
		Language:       CooklangLanguage,
		HighlightQuery: cooklangHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("cooklang"),
	})
}

const cooklangHighlightQuery = ""
