package grammars

import (
	"strings"
	"testing"

	"github.com/odvcencio/gotreesitter"
)

// sexpr builds a tree-sitter-style S-expression from a parse tree,
// including only named nodes.
func sexpr(n *gotreesitter.Node, lang *gotreesitter.Language) string {
	if n == nil {
		return ""
	}
	name := n.Type(lang)
	if !n.IsNamed() {
		return ""
	}
	if n.ChildCount() == 0 {
		return "(" + name + ")"
	}
	var parts []string
	for i := 0; i < n.ChildCount(); i++ {
		s := sexpr(n.Child(i), lang)
		if s != "" {
			parts = append(parts, s)
		}
	}
	if len(parts) == 0 {
		return "(" + name + ")"
	}
	return "(" + name + " " + strings.Join(parts, " ") + ")"
}

// Golden S-expressions for top 20 languages. Generated by parsing each smoke
// sample and recording the tree structure. Changes here indicate parser or
// grammar regressions.
var correctnessGoldens = map[string]string{
	"bash":       "(program (command (command_name (word)) (word)))",
	"c":          "(translation_unit (function_definition (primitive_type) (function_declarator (identifier) (parameter_list (parameter_declaration (primitive_type)))) (compound_statement (return_statement (number_literal)))))",
	"cpp":        "(translation_unit (function_definition (primitive_type) (function_declarator (identifier) (parameter_list)) (compound_statement (return_statement (number_literal)))))",
	"css":        "(stylesheet (rule_set (selectors (tag_name)) (block (declaration (property_name) (plain_value)))))",
	"elixir":     "(source (call (identifier) (arguments (alias)) (do_block (call (identifier) (arguments (call (identifier) (arguments (identifier))) (keywords (pair (keyword) (identifier))))))))",
	"go":         "(source_file (package_clause (package_identifier)) (function_declaration (identifier) (parameter_list) (block (statement_list (expression_statement (call_expression (identifier) (argument_list (int_literal))))))))",
	"html":       "(document (element (start_tag (tag_name)) (element (start_tag (tag_name)) (text) (end_tag (tag_name))) (end_tag (tag_name))) (text))",
	"java":       "(program (class_declaration (identifier) (class_body (field_declaration (integral_type) (variable_declarator (identifier))))))",
	"javascript": "(program (function_declaration (identifier) (formal_parameters) (statement_block (return_statement (number)))) (lexical_declaration (variable_declarator (identifier) (arrow_function (formal_parameters) (binary_expression (identifier) (number))))))",
	"json":       "(document (object (pair (string (string_content)) (number))))",
	"kotlin":     "(source_file (function_declaration (simple_identifier) (function_value_parameters) (function_body (statements (property_declaration (binding_pattern_kind) (variable_declaration (simple_identifier) (nullable_type (user_type (type_identifier)) (quest))) (null_literal)) (call_expression (simple_identifier) (call_suffix (value_arguments (value_argument (simple_identifier)))))))))",
	"lua":        "(chunk (variable_declaration (assignment_statement (variable_list (identifier)) (expression_list (number)))))",
	"php":        "(program (php_tag) (echo_statement (integer)))",
	"python":     "(module (function_definition (identifier) (parameters) (block (return_statement (integer)))))",
	"ruby":       "(program (method (identifier) (body_statement (integer))))",
	"rust":       "(source_file (function_item (identifier) (parameters) (block (let_declaration (identifier) (integer_literal)))))",
	"scala":      "(compilation_unit (object_definition (identifier) (template_body (function_definition (identifier) (parameters (parameter (identifier) (type_identifier))) (type_identifier) (infix_expression (identifier) (operator_identifier) (integer_literal))))))",
	"toml":       "(document (pair (bare_key) (integer)) (pair (bare_key) (string)) (pair (bare_key) (array (string) (string))))",
	"typescript": "(program (function_declaration (identifier) (formal_parameters) (type_annotation (predefined_type)) (statement_block (return_statement (number)))))",
	"yaml":       "(stream (document (block_node (block_mapping (block_mapping_pair (flow_node (plain_scalar (string_scalar))) (flow_node (plain_scalar (integer_scalar))))))))",
}

func TestCorrectnessSnapshots(t *testing.T) {
	entries := AllLanguages()
	entryByName := make(map[string]LangEntry, len(entries))
	for _, e := range entries {
		entryByName[e.Name] = e
	}

	reports := AuditParseSupport()
	reportByName := make(map[string]ParseSupport, len(reports))
	for _, r := range reports {
		reportByName[r.Name] = r
	}

	for name, golden := range correctnessGoldens {
		t.Run(name, func(t *testing.T) {
			entry, ok := entryByName[name]
			if !ok {
				t.Fatalf("language %q not registered", name)
			}
			report := reportByName[name]
			sample := parseSmokeSample(name)
			lang := entry.Language()
			parser := gotreesitter.NewParser(lang)
			src := []byte(sample)

			var tree *gotreesitter.Tree
			var parseErr error
			switch report.Backend {
			case ParseBackendTokenSource:
				ts := entry.TokenSourceFactory(src, lang)
				tree, parseErr = parser.ParseWithTokenSource(src, ts)
			case ParseBackendDFA, ParseBackendDFAPartial:
				tree, parseErr = parser.Parse(src)
			default:
				t.Fatalf("unsupported backend %q", report.Backend)
			}
			if parseErr != nil {
				t.Fatalf("parse failed: %v", parseErr)
			}

			if tree == nil || tree.RootNode() == nil {
				t.Fatal("parse returned nil root")
			}

			got := sexpr(tree.RootNode(), lang)
			if got != golden {
				t.Errorf("S-expression mismatch\ngot:  %s\nwant: %s", got, golden)
			}
		})
	}
}
