// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "crystal",
		Extensions:     []string{".cr"},
		Language:       CrystalLanguage,
		HighlightQuery: crystalHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("crystal"),
	})
}

const crystalHighlightQuery = ""
