// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "csv",
		Extensions:     nil,
		Language:       CsvLanguage,
		HighlightQuery: csvHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("csv"),
	})
}

const csvHighlightQuery = ""
