// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "cuda",
		Extensions:     nil,
		Language:       CudaLanguage,
		HighlightQuery: cudaHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("cuda"),
	})
}

const cudaHighlightQuery = "; inherits: cpp\n\n[\n  \"<<<\"\n  \">>>\"\n] @punctuation.bracket\n\n[\n  \"__host__\"\n  \"__device__\"\n  \"__global__\"\n  \"__managed__\"\n  \"__forceinline__\"\n  \"__noinline__\"\n] @keyword.modifier\n\n\"__launch_bounds__\" @keyword.modifier\n"
