// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "desktop",
		Extensions:     nil,
		Language:       DesktopLanguage,
		HighlightQuery: desktopHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("desktop"),
	})
}

const desktopHighlightQuery = ""
