// Code generated by ts2go batch, then manually extended with TagsQuery.

package grammars

const disassemblyTagsQuery = `
(identifier) @name @definition.function
`

func init() {
	Register(LangEntry{
		Name:               "disassembly",
		Extensions:         []string{".dis", ".dump"},
		Language:            DisassemblyLanguage,
		HighlightQuery:     disassemblyHighlightQuery,
		TagsQuery:          disassemblyTagsQuery,
		TokenSourceFactory: defaultTokenSourceFactory("disassembly"),
	})
}

const disassemblyHighlightQuery = "(byte) @constant\n\n[\n  (address)\n  (hexadecimal)\n  (integer)\n] @number\n\n(identifier) @variable\n\n(bad_instruction) @text.warning\n(code_location (identifier) @function.call)\n(comment) @comment\n(instruction) @function\n(memory_dump) @string\n\n[\"<\" \">\"] @punctuation.special\n[\"+\" \":\"] @punctuation.delimiter\n"
