// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "dtd",
		Extensions:     nil,
		Language:       DtdLanguage,
		HighlightQuery: dtdHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("dtd"),
	})
}

const dtdHighlightQuery = ""
