// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "ebnf",
		Extensions:     nil,
		Language:       EbnfLanguage,
		HighlightQuery: ebnfHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("ebnf"),
	})
}

const ebnfHighlightQuery = ""
