// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "editorconfig",
		Extensions:     nil,
		Language:       EditorconfigLanguage,
		HighlightQuery: editorconfigHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("editorconfig"),
	})
}

const editorconfigHighlightQuery = ""
