// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "eds",
		Extensions:     nil,
		Language:       EdsLanguage,
		HighlightQuery: edsHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("eds"),
	})
}

const edsHighlightQuery = ""
