// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "eex",
		Extensions:     nil,
		Language:       EexLanguage,
		HighlightQuery: eexHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("eex"),
	})
}

const eexHighlightQuery = "; wrapping in (directive .. ) prevents us from highlighting '%>' in a comment as a keyword\n(directive [\"<%\" \"<%=\" \"<%%\" \"<%%=\" \"%>\"] @keyword)\n\n(comment) @comment\n"
