// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "embedded_template",
		Extensions:     []string{".erb", ".ejs"},
		Language:       EmbeddedTemplateLanguage,
		HighlightQuery: embeddedTemplateHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("embedded_template"),
	})
}

const embeddedTemplateHighlightQuery = "(comment_directive) @comment\n\n[\n  \"<%#\"\n  \"<%\"\n  \"<%=\"\n  \"<%_\"\n  \"<%-\"\n  \"%>\"\n  \"-%>\"\n  \"_%>\"\n] @keyword\n"
