// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "fennel",
		Extensions:     nil,
		Language:       FennelLanguage,
		HighlightQuery: fennelHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("fennel"),
	})
}

const fennelHighlightQuery = ""
