// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "gdscript",
		Extensions:     []string{".gd"},
		Language:       GdscriptLanguage,
		HighlightQuery: gdscriptHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("gdscript"),
	})
}

const gdscriptHighlightQuery = ""
