// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "gitignore",
		Extensions:     []string{".gitignore"},
		Language:       GitignoreLanguage,
		HighlightQuery: gitignoreHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("gitignore"),
	})
}

const gitignoreHighlightQuery = ""
