// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "godot_resource",
		Extensions:     []string{".tres", ".tscn"},
		Language:       GodotResourceLanguage,
		HighlightQuery: godotResourceHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("godot_resource"),
	})
}

const godotResourceHighlightQuery = ""
