// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "gomod",
		Extensions:     nil,
		Language:       GomodLanguage,
		HighlightQuery: gomodHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("gomod"),
	})
}

const gomodHighlightQuery = "[\n  \"require\"\n  \"replace\"\n  \"go\"\n  \"toolchain\"\n  \"exclude\"\n  \"retract\"\n  \"module\"\n] @keyword\n\n\"=>\" @operator\n\n(comment) @comment\n\n[\n(version)\n(go_version)\n] @string\n"
