// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "graphql",
		Extensions:     []string{".graphql", ".gql"},
		Language:       GraphqlLanguage,
		HighlightQuery: graphqlHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("graphql"),
	})
}

const graphqlHighlightQuery = ""
