// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "hcl",
		Extensions:     []string{".hcl", ".tf", ".tfvars"},
		Language:       HclLanguage,
		HighlightQuery: hclHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("hcl"),
	})
}

const hclHighlightQuery = ""
