// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "hlsl",
		Extensions:     []string{".hlsl", ".fx"},
		Language:       HlslLanguage,
		HighlightQuery: hlslHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("hlsl"),
	})
}

const hlslHighlightQuery = ""
