// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "html",
		Extensions:     []string{".html", ".htm"},
		Language:       HtmlLanguage,
		HighlightQuery: htmlHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("html"),
	})
}

const htmlHighlightQuery = "(tag_name) @tag\n(erroneous_end_tag_name) @tag.error\n(doctype) @constant\n(attribute_name) @attribute\n(attribute_value) @string\n(comment) @comment\n\n[\n  \"<\"\n  \">\"\n  \"</\"\n  \"/>\"\n] @punctuation.bracket\n"
