// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "hyprlang",
		Extensions:     []string{".conf"},
		Language:       HyprlangLanguage,
		HighlightQuery: hyprlangHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("hyprlang"),
	})
}

const hyprlangHighlightQuery = ""
