// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "ini",
		Extensions:     []string{".ini", ".cfg", ".conf"},
		Language:       IniLanguage,
		HighlightQuery: iniHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("ini"),
	})
}

const iniHighlightQuery = "(section_name\n  (text) @type) ; consistency with toml\n\n(comment) @comment @spell\n\n[\n  \"[\"\n  \"]\"\n] @punctuation.bracket\n\n\"=\" @operator\n\n(setting\n  (setting_name) @property)\n\n; (setting_value) @none ; grammar does not support subtypes\n"
