// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "janet",
		Extensions:     []string{".janet"},
		Language:       JanetLanguage,
		HighlightQuery: janetHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("janet"),
	})
}

const janetHighlightQuery = "(num_lit) @number\n\n[\n (buf_lit)\n (long_buf_lit)\n (long_str_lit)\n (str_lit)\n] @string\n\n[\n (bool_lit)\n (nil_lit)\n] @constant.builtin\n\n(kwd_lit) @constant\n\n(comment) @comment\n\n;; Treat quasiquotation as operators for the purpose of highlighting.\n\n[\n \"'\"\n \"~\"\n \",\"\n] @operator\n"
