// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "jinja2",
		Extensions:     []string{".j2", ".jinja2", ".jinja"},
		Language:       Jinja2Language,
		HighlightQuery: jinja2HighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("jinja2"),
	})
}

const jinja2HighlightQuery = ""
