// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "jsdoc",
		Extensions:     nil,
		Language:       JsdocLanguage,
		HighlightQuery: jsdocHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("jsdoc"),
	})
}

const jsdocHighlightQuery = "(tag_name) @keyword\n(type) @type\n"
