// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "json",
		Extensions:     []string{".json"},
		Language:       JsonLanguage,
		HighlightQuery: jsonHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("json"),
	})
}

const jsonHighlightQuery = "(pair\n  key: (_) @string.special.key)\n\n(string) @string\n\n(number) @number\n\n[\n  (null)\n  (true)\n  (false)\n] @constant.builtin\n\n(escape_sequence) @escape\n\n(comment) @comment\n"
