// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "json5",
		Extensions:     []string{".json5"},
		Language:       Json5Language,
		HighlightQuery: json5HighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("json5"),
	})
}

const json5HighlightQuery = "(string) @string\n\n(identifier) @constant\n\n(number) @constant.numeric\n\n(null) @constant.builtin\n\n[(true) (false)] @constant.builtin.boolean\n\n(comment) @comment\n"
