// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "just",
		Extensions:     nil,
		Language:       JustLanguage,
		HighlightQuery: justHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("just"),
	})
}

const justHighlightQuery = ""
