// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "ledger",
		Extensions:     []string{".ledger", ".journal"},
		Language:       LedgerLanguage,
		HighlightQuery: ledgerHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("ledger"),
	})
}

const ledgerHighlightQuery = ""
