// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "markdown",
		Extensions:     []string{".md"},
		Language:       MarkdownLanguage,
		HighlightQuery: markdownHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("markdown"),
	})
}

const markdownHighlightQuery = ""
