// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "matlab",
		Extensions:     []string{".m", ".mat"},
		Language:       MatlabLanguage,
		HighlightQuery: matlabHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("matlab"),
	})
}

const matlabHighlightQuery = ""
