// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "move",
		Extensions:     []string{".move"},
		Language:       MoveLanguage,
		HighlightQuery: moveHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("move"),
	})
}

const moveHighlightQuery = ""
