// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "norg",
		Extensions:     []string{".norg"},
		Language:       NorgLanguage,
		HighlightQuery: norgHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("norg"),
	})
}

const norgHighlightQuery = ""
