// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "nushell",
		Extensions:     []string{".nu"},
		Language:       NushellLanguage,
		HighlightQuery: nushellHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("nushell"),
	})
}

const nushellHighlightQuery = ""
