// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "pem",
		Extensions:     []string{".pem"},
		Language:       PemLanguage,
		HighlightQuery: pemHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("pem"),
	})
}

const pemHighlightQuery = "[ \"BEGIN\" \"END\" ] @keyword\n\n(dashes) @punctuation.delimiter\n\n(label) @type\n\n(data) @markup\n\n(comment) @comment\n"
