// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "prolog",
		Extensions:     []string{".pl", ".pro"},
		Language:       PrologLanguage,
		HighlightQuery: prologHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("prolog"),
	})
}

const prologHighlightQuery = ""
