// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "promql",
		Extensions:     []string{".promql"},
		Language:       PromqlLanguage,
		HighlightQuery: promqlHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("promql"),
	})
}

const promqlHighlightQuery = ""
