// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "rst",
		Extensions:     []string{".rst"},
		Language:       RstLanguage,
		HighlightQuery: rstHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("rst"),
	})
}

const rstHighlightQuery = ""
