// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "sparql",
		Extensions:     []string{".rq", ".sparql"},
		Language:       SparqlLanguage,
		HighlightQuery: sparqlHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("sparql"),
	})
}

const sparqlHighlightQuery = ""
