// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "swift",
		Extensions:     []string{".swift"},
		Language:       SwiftLanguage,
		HighlightQuery: swiftHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("swift"),
	})
}

const swiftHighlightQuery = ""
