// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "tcl",
		Extensions:     []string{".tcl"},
		Language:       TclLanguage,
		HighlightQuery: tclHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("tcl"),
	})
}

const tclHighlightQuery = ""
