// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "templ",
		Extensions:     []string{".templ"},
		Language:       TemplLanguage,
		HighlightQuery: templHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("templ"),
	})
}

const templHighlightQuery = ""
