// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "tmux",
		Extensions:     nil,
		Language:       TmuxLanguage,
		HighlightQuery: tmuxHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("tmux"),
	})
}

const tmuxHighlightQuery = ""
