// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "todotxt",
		Extensions:     nil,
		Language:       TodotxtLanguage,
		HighlightQuery: todotxtHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("todotxt"),
	})
}

const todotxtHighlightQuery = "(done_task) @comment\n(task (priority) @keyword)\n(task (date) @comment)\n(task (kv) @comment)\n(task (project) @string)\n(task (context) @type)\n"
