// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "turtle",
		Extensions:     []string{".ttl"},
		Language:       TurtleLanguage,
		HighlightQuery: turtleHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("turtle"),
	})
}

const turtleHighlightQuery = ""
