// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "typst",
		Extensions:     []string{".typ"},
		Language:       TypstLanguage,
		HighlightQuery: typstHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("typst"),
	})
}

const typstHighlightQuery = ""
