// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "verilog",
		Extensions:     []string{".v", ".sv", ".svh"},
		Language:       VerilogLanguage,
		HighlightQuery: verilogHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("verilog"),
	})
}

const verilogHighlightQuery = ""
