// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "vhdl",
		Extensions:     []string{".vhd", ".vhdl"},
		Language:       VhdlLanguage,
		HighlightQuery: vhdlHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("vhdl"),
	})
}

const vhdlHighlightQuery = ""
