// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "vimdoc",
		Extensions:     nil,
		Language:       VimdocLanguage,
		HighlightQuery: vimdocHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("vimdoc"),
	})
}

const vimdocHighlightQuery = ""
