// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "vue",
		Extensions:     []string{".vue"},
		Language:       VueLanguage,
		HighlightQuery: vueHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("vue"),
	})
}

const vueHighlightQuery = ""
