// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "wolfram",
		Extensions:     []string{".wl", ".m", ".nb"},
		Language:       WolframLanguage,
		HighlightQuery: wolframHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("wolfram"),
	})
}

const wolframHighlightQuery = "(symbol) @symbol\n"
