// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "xml",
		Extensions:     []string{".xml"},
		Language:       XmlLanguage,
		HighlightQuery: xmlHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("xml"),
	})
}

const xmlHighlightQuery = ""
