package grammars

import "github.com/odvcencio/gotreesitter"

// scanner_attachments.go — NOT generated by ts2go batch.
//
// This file re-attaches hand-written external scanners to their
// respective Language objects. Because ts2go batch overwrites
// *_register.go files on every regen, any ExternalScanner wiring
// placed there would be lost. Keeping it here means scanners survive
// future batch runs.
//
// init() order within a Go package is alphabetical by filename.
// This file starts with "zzz_" to ensure it runs AFTER all
// *_register.go files, so registry entries exist when this init runs.

func init() {
	attachments := map[string]gotreesitter.ExternalScanner{
		"python":  PythonExternalScanner{},
		"elixir":  ElixirExternalScanner{},
		"comment": CommentExternalScanner{},
		"doxygen": DoxygenExternalScanner{},
		"foam":    FoamExternalScanner{},
		"nginx":   NginxExternalScanner{},
		"nushell": NushellExternalScanner{},
		"r":       RExternalScanner{},
		"xml":        XMLExternalScanner{},
		"yuck":       YuckExternalScanner{},
		"purescript": PurescriptExternalScanner{},
		"typst":      TypstExternalScanner{},
		// New hand-written scanners:
		"jsdoc":      JsdocExternalScanner{},
		"gleam":      GleamExternalScanner{},
		"scss":       ScssExternalScanner{},
		"css":        CssExternalScanner{},
		"erlang":     ErlangExternalScanner{},
		"sql":        SqlExternalScanner{},
		"dockerfile": DockerfileExternalScanner{},
		"dart":       DartExternalScanner{},
		"kotlin":     KotlinExternalScanner{},
		"ocaml":      OcamlExternalScanner{},
		"wgsl":         WgslExternalScanner{},
		"tablegen":     TablegenExternalScanner{},
		"less":         LessExternalScanner{},
		"properties":   PropertiesExternalScanner{},
		"cooklang":     CooklangExternalScanner{},
		"dhall":        DhallExternalScanner{},
		"kdl":          KdlExternalScanner{},
		"editorconfig": EditorconfigExternalScanner{},
		"janet":        JanetExternalScanner{},
		"cuda":         CudaExternalScanner{},
		"arduino":      ArduinoExternalScanner{},
		"hlsl":         HlslExternalScanner{},
		"jsonnet":      JsonnetExternalScanner{},
		"tcl":          TclExternalScanner{},
		"bicep":        BicepExternalScanner{},
		"ron":          RonExternalScanner{},
		"beancount":    BeancountExternalScanner{},
		"dtd":          DtdExternalScanner{},
		"nix":          NixExternalScanner{},
		"luau":         LuauExternalScanner{},
		"liquid":         LiquidExternalScanner{},
		"wolfram":        WolframExternalScanner{},
		"squirrel":       SquirrelExternalScanner{},
		"uxntal":         UxntalExternalScanner{},
		"gn":             GnExternalScanner{},
		"godot_resource": GodotResourceExternalScanner{},
		"kconfig":        KconfigExternalScanner{},
		"haxe":           HaxeExternalScanner{},
		"fish":           FishExternalScanner{},
		"cue":            CueExternalScanner{},
		"powershell":     PowershellExternalScanner{},
		"racket":         RacketExternalScanner{},
		"earthfile":      EarthfileExternalScanner{},
		"awk":            AwkExternalScanner{},
		"firrtl":         FirrtlExternalScanner{},
		"just":           JustExternalScanner{},
		"cairo":          CairoExternalScanner{},
		"gitcommit":      GitcommitExternalScanner{},
		"cmake":          CmakeExternalScanner{},
		"teal":           TealExternalScanner{},
		"templ":          TemplExternalScanner{},
		"org":            OrgExternalScanner{},
		"odin":           OdinExternalScanner{},
		"tsx":            TsxExternalScanner{},
		"d":              DExternalScanner{},
		"nickel":         NickelExternalScanner{},
		"pug":            PugExternalScanner{},
		"agda":           AgdaExternalScanner{},
		"fennel":         FennelExternalScanner{},
		"cobol":          CobolExternalScanner{},
		"hack":           HackExternalScanner{},
		"starlark":       StarlarkExternalScanner{},
		"julia":          JuliaExternalScanner{},
		"pkl":            PklExternalScanner{},
		"c_sharp":        CSharpExternalScanner{},
		"mojo":           MojoExternalScanner{},
		"blade":          BladeExternalScanner{},
		"angular":        AngularExternalScanner{},
		"vue":            VueExternalScanner{},
		"astro":          AstroExternalScanner{},
		"gdscript":       GdscriptExternalScanner{},
		"elm":            ElmExternalScanner{},
		"disassembly":    DisassemblyExternalScanner{},
		"bitbake":        BitbakeExternalScanner{},
		"scala":           ScalaExternalScanner{},
		"php":             PhpExternalScanner{},
		"fsharp":          FsharpExternalScanner{},
		"fortran":         FortranExternalScanner{},
		"markdown_inline": MarkdownInlineExternalScanner{},
		"matlab":          MatlabExternalScanner{},
		"tlaplus":         TlaplusExternalScanner{},
		"markdown":        MarkdownExternalScanner{},
		"nim":             NimExternalScanner{},
		"bash":            BashExternalScanner{},
		"ruby":            RubyExternalScanner{},
		"perl":            PerlExternalScanner{},
		"crystal":         CrystalExternalScanner{},
		"djot":            DjotExternalScanner{},
		"cpp":             CppExternalScanner{},
		"caddy":           CaddyExternalScanner{},
		"javascript":      JavaScriptExternalScanner{},
		"typescript":      TypeScriptExternalScanner{},
		"rust":            RustExternalScanner{},
		"hcl":             HclExternalScanner{},
		"rescript":        RescriptExternalScanner{},
		"svelte":          SvelteExternalScanner{},
		"rst":             RstExternalScanner{},
		"haskell":         HaskellExternalScanner{},
		"vhdl":            VhdlExternalScanner{},
	}

	for i := range registry {
		if scanner, ok := attachments[registry[i].Name]; ok {
			orig := registry[i].Language
			s := scanner // capture for closure
			registry[i].Language = func() *gotreesitter.Language {
				lang := orig()
				lang.ExternalScanner = s
				return lang
			}
		}
	}
}
